### ISSUE TITLE
not work `docker::install`

### ISSUE THREAD

**Issue by letusfly85** [k0kubun/itamae-plugin-recipe-docker#2]
Hi, I tried to use this library.
however it didn't work.

```ruby
# Install Docker, start it and ensure it starts on boot.
include_recipe "docker::install"

docker:
  # Users who is added to docker group (optional)
  users:
    - ubuntu
```

```bash
INFO : Starting Itamae...
/home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/itamae-1.9.3/lib/itamae/recipe.rb:58:in `instance_eval': /home/ubuntu/work/docker-recipe.rb:4: syntax error, unexpected ':', expecting end-of-input (SyntaxError)
        from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/itamae-1.9.3/lib/itamae/recipe.rb:58:in `load'
        from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/itamae-1.9.3/lib/itamae/runner.rb:49:in `block in load_recipes'
        from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/itamae-1.9.3/lib/itamae/runner.rb:40:in `each'
        from /home/ubuntu/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/itamae-1.9.3/lib/itamae/runner.rb:40:in `load_recipes'
```

**Comment by k0kubun** [comment]
I'm sorry to write such a confusing README. Updated usage in it.
https://github.com/k0kubun/itamae-plugin-recipe-docker#usage

Actually, lines after `docker:` should be a separate file, which is node.yml. 
`include_reciep "docker::install"` is the only part which should be included in the recipe.

**Comment by k0kubun** [comment]
Please try this later. Closing for now but reopen if you still have some problem.
